# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abhilasha/Dev/Programming/C++/Scrabble

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abhilasha/Dev/Programming/C++/Scrabble

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abhilasha/Dev/Programming/C++/Scrabble/CMakeFiles /home/abhilasha/Dev/Programming/C++/Scrabble//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abhilasha/Dev/Programming/C++/Scrabble/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scrabble

# Build rule for target.
scrabble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scrabble
.PHONY : scrabble

# fast build rule for target.
scrabble/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/build
.PHONY : scrabble/fast

#=============================================================================
# Target rules for targets named scrabble_test

# Build rule for target.
scrabble_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scrabble_test
.PHONY : scrabble_test

# fast build rule for target.
scrabble_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble_test.dir/build.make CMakeFiles/scrabble_test.dir/build
.PHONY : scrabble_test/fast

src/board.o: src/board.cpp.o
.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/helper.o: src/helper.cpp.o
.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i
.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s
.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/wordlist.o: src/wordlist.cpp.o
.PHONY : src/wordlist.o

# target to build an object file
src/wordlist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/wordlist.cpp.o
.PHONY : src/wordlist.cpp.o

src/wordlist.i: src/wordlist.cpp.i
.PHONY : src/wordlist.i

# target to preprocess a source file
src/wordlist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/wordlist.cpp.i
.PHONY : src/wordlist.cpp.i

src/wordlist.s: src/wordlist.cpp.s
.PHONY : src/wordlist.s

# target to generate assembly for a file
src/wordlist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble.dir/build.make CMakeFiles/scrabble.dir/src/wordlist.cpp.s
.PHONY : src/wordlist.cpp.s

tests/test_gtest.o: tests/test_gtest.cpp.o
.PHONY : tests/test_gtest.o

# target to build an object file
tests/test_gtest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble_test.dir/build.make CMakeFiles/scrabble_test.dir/tests/test_gtest.cpp.o
.PHONY : tests/test_gtest.cpp.o

tests/test_gtest.i: tests/test_gtest.cpp.i
.PHONY : tests/test_gtest.i

# target to preprocess a source file
tests/test_gtest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble_test.dir/build.make CMakeFiles/scrabble_test.dir/tests/test_gtest.cpp.i
.PHONY : tests/test_gtest.cpp.i

tests/test_gtest.s: tests/test_gtest.cpp.s
.PHONY : tests/test_gtest.s

# target to generate assembly for a file
tests/test_gtest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scrabble_test.dir/build.make CMakeFiles/scrabble_test.dir/tests/test_gtest.cpp.s
.PHONY : tests/test_gtest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... scrabble"
	@echo "... scrabble_test"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/wordlist.o"
	@echo "... src/wordlist.i"
	@echo "... src/wordlist.s"
	@echo "... tests/test_gtest.o"
	@echo "... tests/test_gtest.i"
	@echo "... tests/test_gtest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

