#include "../include/helper.h"

Square board_layout[225] = {
        TRIPLE_WORD, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, TRIPLE_WORD, 
        EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY,
        EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, 
        DOUBLE_LETTER, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, DOUBLE_LETTER,
        EMPTY, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, EMPTY, 
        EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, 
        EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, 
        TRIPLE_WORD, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, TRIPLE_WORD,
        EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, 
        EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, 
        EMPTY, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, EMPTY, 
        DOUBLE_LETTER, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, DOUBLE_LETTER,
        EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY, EMPTY, 
        EMPTY, DOUBLE_WORD, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_LETTER, EMPTY, EMPTY, EMPTY, DOUBLE_WORD, EMPTY,
        TRIPLE_WORD, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, EMPTY, TRIPLE_WORD, EMPTY, EMPTY, EMPTY, DOUBLE_LETTER, EMPTY, EMPTY, TRIPLE_WORD
};


score_t get_score(std::string word){
        score_t score = 0;
        for(auto tile : word){
                score += tile_scores[tile - 'A'];
        }
        return score;
}
